language: generic
sudo: required
services:
  - docker:
before_install:
  - docker build -t prashantbhat84/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true prashantbhat84/react-test npm test

after_success:
  - docker build -t prashantbhat84/multi-client ./client
  - docker build -t prashantbhat84/multi-nginx ./nginx
  - docker build -t prashantbhat84/multi-server ./server
  - docker build -t prashantbhat84/multi-worker ./workers
  # login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  # take those images and push to docker hub
  - docker push prashantbhat84/multi-client
  - docker push prashantbhat84/multi-nginx
  - docker push prashantbhat84/multi-server
  - docker push prashantbhat84/multi-worker
